#### NumPy - Basic Operations

##### Mathematical Operations

In [1]:
import numpy as np

In [2]:
#addition
np.add(45,20)

65

In [3]:
#subtraction
np.subtract(45,23)

22

In [4]:
# ndarray multiplication
# create ndarray which conntains number of hrs worked for 5 days
# hourly rate is 15 USD
np_daily_wage = np.array([7,9,13,8,11])*15

In [5]:
np_daily_wage

array([105, 135, 195, 120, 165])

In [6]:
#total earning after 5 days
#use sum method to add all data elements of ndarray
sum(np_daily_wage)

720

In [7]:
#print hourly wage for each day
print (np_daily_wage)

[105 135 195 120 165]


In [8]:
np_daily_wage

array([105, 135, 195, 120, 165])

##### Comparison Operations

In [9]:
#comparison operations
#create ndarray for weekly hrs, 5 consecutive weeks hrs data
np_weekly_hrs = np.array([23,41,55,47,38])

In [10]:
mask = np_weekly_hrs>40

In [11]:
mask

array([False,  True,  True,  True, False])

In [12]:
#week with more than 40 hrs 
np_weekly_hrs[mask]

array([41, 55, 47])

In [ ]:
#week with hrs not equals to 40
np_weekly_hrs[np_weekly_hrs!=40]

##### Logical Operations

In [13]:
#Logical AND operation
np.logical_and(np_weekly_hrs>20,np_weekly_hrs<50)

array([ True,  True, False,  True,  True])

In [14]:
#Logical NOT operation
np.logical_not(np_weekly_hrs>35)

array([ True, False, False, False, False])