In [1]:
#import NumPy library
import numpy as np

In [2]:
#first NumPy arrayp
first_numpy_array = np.array([1,2,3,4])

In [3]:
#print first array
first_numpy_array

array([1, 2, 3, 4])

In [4]:
#array with zeros
array_with_zeros = np.zeros((3,3))
array_with_zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
#array with ones
array_with_ones = np.ones((3,3))
array_with_ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
#array with empty
array_with_empty = np.empty((1,3))
array_with_empty

array([[0.00000000e+000, 0.00000000e+000, 1.49457702e-154]])

In [14]:
#array with arange method
np_arange = np.arange(12)

In [15]:
#print array
np_arange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [17]:
#reshape method to change/ create array
np_arange.reshape(3,4).T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [19]:
#linspace for linearly (equal) spaced data elements
np_linspce = np.linspace(start=1,stop=6,num=5)

In [20]:
#print linespaced array
np_linspce

array([1.  , 2.25, 3.5 , 4.75, 6.  ])

In [21]:
#One dimensional array
oneD_array = np.arange(15)

In [22]:
#print 1D array
oneD_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [23]:
#Two dimensional array
TwoD_array = oneD_array.reshape(3,5)

In [24]:
#print 2D array
TwoD_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [25]:
#Three dimensional array
ThreeD_array = np.arange(27).reshape(3,3,3)

In [26]:
#Print 3D array
ThreeD_array

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [27]:
# broadcasting
a = np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [28]:
b = np.arange(3)
b

array([0, 1, 2])

In [29]:
a.shape

(3, 3)

In [30]:
a.size

9

In [31]:
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [32]:
b

array([0, 1, 2])

In [33]:
a + b

array([[0., 1., 2.],
       [0., 1., 2.],
       [0., 1., 2.]])

In [35]:
print(a.shape)
print(b.shape)

(3, 3)
(3,)


In [ ]:
b --> [[0,1,2],[0,1,2],[0,1,2]]

In [ ]:
b --> [[0,0,0],[1,1,1],[2,2,2]]

In [38]:
b.shape

(3,)

In [39]:
b[None].shape

(1, 3)

In [41]:
a + b

array([[0., 1., 2.],
       [0., 1., 2.],
       [0., 1., 2.]])

In [44]:
b[:,None].shape

(3, 1)

In [45]:
a + b

array([[0., 1., 2.],
       [0., 1., 2.],
       [0., 1., 2.]])

In [46]:
a+ b[:, None]

array([[0., 0., 0.],
       [1., 1., 1.],
       [2., 2., 2.]])

In [47]:
b[:,None, None, None]

array([[[[0]]],


       [[[1]]],


       [[[2]]]])

In [50]:
b[:,None, None, None].ravel().shape

(3,)